{% set version = "3.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rainbow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rainbow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rainbow/rainbow_{{ version }}.tar.gz
  sha256: 63d1246f88a498f3db0321b46a552163631b288a25b24400935db41326636e87

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-cluster
    - r-colorspace
    - r-hdrcde
    - r-ks
    - r-pcapp
  run:
    - r-base
    - r-mass
    - r-cluster
    - r-colorspace
    - r-hdrcde
    - r-ks
    - r-pcapp

test:
  commands:
    - $R -e "library('rainbow')"           # [not win]
    - "\"%R%\" -e \"library('rainbow')\""  # [win]

about:
  home: https://sites.google.com/site/hanlinshangswebsite/
  license: GPL (>= 2)
  summary: Visualizing functional data and identifying functional outliers.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
