{% set version = "3.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rainbow
  version: {{ version|replace("-", "_") }}

source:
  fn: rainbow_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rainbow_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rainbow/rainbow_{{ version }}.tar.gz
  sha256: 135d9f0fcf8798076111a154fab315b64b30e2dbc4504efae5892b3816758abd

build:
  number: 0
  # r-hdrcde not build for win and osx
  skip: true  # [win or osx]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-mass
    - r-cluster
    - r-colorspace
    - r-hdrcde
    - r-ks
    - r-pcapp

  run:
    - r-base
    - r-mass
    - r-cluster
    - r-colorspace
    - r-hdrcde
    - r-ks
    - r-pcapp

test:
  commands:
    - $R -e "library('rainbow')"  # [not win]
    - "\"%R%\" -e \"library('rainbow')\""  # [win]

about:
  home: https://sites.google.com/site/hanlinshangswebsite/
  license: GPL (>= 2)
  summary: Functions and data sets for functional data display and outlier detection.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
