{% set version = "3.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rainbow
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rainbow_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rainbow/rainbow_{{ version }}.tar.gz
  sha256: eca456288b70fe4b6c74a587d8624d3b36d67f8f9ffc13320eefb17a952d823d

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-mass
    - r-cluster
    - r-colorspace
    - r-hdrcde
    - r-ks
    - r-pcapp
  run:
    - r-base
    - r-mass
    - r-cluster
    - r-colorspace
    - r-hdrcde
    - r-ks
    - r-pcapp

test:
  commands:
    - $R -e "library('rainbow')"           # [not win]
    - "\"%R%\" -e \"library('rainbow')\""  # [win]

about:
  home: https://sites.google.com/site/hanlinshangswebsite/
  license: GPL (>= 2)
  summary: Visualizing functional data and identifying functional outliers.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
