travis:
  secure:
    BINSTAR_TOKEN: QX/BtAgGI9KMs4tKNlGAFLGM198pdLr9kKmlqD8+OpxnyV/0uFeMz2+reAJm3EsyBR44b+BAOPCBGtgj97TJRaT4hDfwbG/3A4ctW/FZHmiVIrvIPQWOKQJmDWQ9v1SxIwAnESJ5roCqL0iXRAn+LG3XhBGUijeBpxZwPS4cGlyJ64I+BpAzF9otTCGfm4FUk5MpBpevA3vvZo6ZXiAJOe8CeHtI5G8IYXyh5L/x/1vtdpRnAxqnDOdQ2O3Lg745sNOmBquh1q/4NDMAoujAArXWamuIGgjWYQ7gePnQhLiIJ2CEkBzk5CoVoxwPWajQ3wj+KhQ1fKGqkaaZ4C/Yp1XPyTmtcSz+qZA2x0Qt63pwT01pnPkmE/JS3sGepY7qPH/PM6U8fDeVtSichzTJWliiKQXBgR6OYyh477cEUMM8yzvuc8TnkDMqdaWbzOJKdFXpsrA5rfSy902W50Qbzi82sgoErk8qxnKz1Kv/URDULDVZEIIlGdQnkMoTLh41872ab7mV5Hz1vkCjAovtR0JDT4ookSUi5w4+ZzD939FMm7mii1MA/WByegidknT+eSLhuUf7apBIg7KaaEBwRUH+GNfMqXzz00s28BsuU2NMFtEjvKGleoiQ1iBpK4k2CI17D7/HhDXpaEKrXRrdBwzu8jQq2NajBaoNUDCjHfs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
